name: Publish distribution to PyPI
on:
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pypa
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build wheel and tarball
        run: python3 -m build
      - name: Store the packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
         
    
  publish-to-pypi:
    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')  # only publish on tag pushes
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/llnl-clippy.py
    permissions:
      id-token: write

    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
      
  
